### ISSUE TITLE
[Google Cloud Script] Check firewall rule existence before deleting

### ISSUE THREAD

**Issue by LucianaMarques** [mlbench/mlbench-helm#8]
Hi there!

Finally I have an instance of mlbench working. I was just in doubt about how to properly quit or finish it, supposing I don't want to leave it running. 

I understand that the setup is done by:

```
$ ./google-cloud-script.sh create-cluster
$ ./google-cloud-script.sh install-chart
```

But what if we want to delete the cluster? I tried to first 'uninstall-chart' and then 'delete-cluster', but if I uninstall the chart first, when trying to delete cluster the proper resources are not found. How to proper procede here? (by the way, when trying to uninstall charts after deleting cluster, connection is refused but I guess that's expected, right?)

Thanks!

**Comment by Panaetius** [comment]
This seems to be due to Line 111 and 185 doing the same thing in https://github.com/mlbench/mlbench-helm/blob/develop/google_cloud_setup.sh#L111 . 

I think the correct way to do it would be to first check if the firewall rule is present when executing the one in Line 111. It's needed in both places, since one might delete the cluster without first deleting the chart/deployment.

**Comment by LucianaMarques** [comment]
@Panaetius ok! Do you mind if I take a look at this? I think this may help me to understand better what the script is doing.

**Comment by Panaetius** [comment]
Sure, thanks for the help.

**Comment by LucianaMarques** [comment]
Hi there, just a quick update, I'm still working on this! I'll come back later with more concrete updates.

**Comment by LucianaMarques** [comment]
I think I just resolved this, I'm sending a PR in some minutes.

**Comment by Panaetius** [comment]
Thanks a lot, it works great :+1:
